# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1604"
  config.vm.provider "virtualbox"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "local-test.yml"
    ansible.host_vars = {
      "default" => {
        "jenkins_master" => ENV["jenkins_master"],
        "jenkins_slave_secret" => ENV["jenkins_slave_secret"],
        "jenkins_slave_user" => "vagrant",
        "jenkins_slave_group" => "vagrant"
      }
    }
    # ansible.verbose = "v"
  end
end